### PR TITLE
Update headers regenerated from latest xml

### PR DESCRIPTION
**Pull request by nikhiljnv**
Update OpenCL headers by regenerating them from
latest XML files to include recent spec updates.

### CODE REVIEW

**Review by EwanC — APPROVED** [review]
LGTM - ran the script locally and this matches what I see

**Review by bashbaug — APPROVED** [review]

**Comment by bashbaug** [comment]
Is this going to need updates to the CTS tests also, for the mutable command buffer changes?

**Comment by EwanC** [comment]
> Is this going to need updates to the CTS tests also, for the mutable command buffer changes?

I think it's just the code comments that are changing here for mutable command-buffers

**Comment by bashbaug** [comment]
> > Is this going to need updates to the CTS tests also, for the mutable command buffer changes?
> 
> I think it's just the code comments that are changing here for mutable command-buffers, so shouldn't be any effect on header users.

Ah right, thanks!  I'll just merge this, then.

**Pull request merged**
