### PR TITLE
Add definitions for cl_arm_protected_memory_allocation

### PR DESCRIPTION
**Pull request by kpet**
Specification: https://github.com/KhronosGroup/OpenCL-Docs/pull/727

Signed-off-by: Kevin Petit <kevin.petit@arm.com>

### CODE REVIEW

**Review by bashbaug — COMMENTED** [review]
Some compilers will emit a warning and generate a poison value for this case: https://godbolt.org/z/dKo3KjThz

I think we'll need something else where we're shifting by more than 31 bits.  Some options:

* `((cl_ulong)1 << 36)` (cl_ulong is always 64-bits)
* `((cl_bitfield)1 << 36)` (cl_bitfield is also always 64-bits)
* `(1ULL << 36)` (long long is guaranteed to be 64-bits in C++11 at least, not sure about others)

I'll update the header generation scripts when we figure out what we want to do.

**Comment by kpet** [comment]
Oh yes, it's undefined behaviour. I've gone for `ULL`. This should have been caught by the CI. Maybe we can use `Werror`. I'll have a look.

**Comment by kpet** [comment]
@bashbaug Could you take another look please? We'd like to get this in ahead of an upcoming release. Thanks!

**Review by bashbaug — APPROVED** [review]
Sorry about the slow reply - this got lost in my notifications. Latest version LGTM.  Merging!

**Pull request merged**
