### PR TITLE
Add definitions for cl_arm_job_slot_selection

### PR DESCRIPTION
**Pull request by kpet**
Signed-off-by: Kevin Petit <kevin.petit@arm.com>

### CODE REVIEW

**Comment by kpet** [comment]
Will push the enumerant declarations once https://github.com/KhronosGroup/OpenCL-Docs/pull/100 goes in. This shouldn't be merged before the enumerant declarations.

**Comment by kpet** [comment]
Enumerant issues are now resolved. The new enumerants are declared with https://github.com/KhronosGroup/OpenCL-Docs/pull/107.

**Comment by kpet** [comment]
The enumerant declarations have gone in. This can now be merged.

**Comment by bashbaug** [comment]
+1, LGTM.

**Comment by kpet** [comment]
Thanks for the review, merging.

**Pull request merged**
