### PR TITLE
Add CMake Packaging + CI For Package

### PR DESCRIPTION
**Pull request by sl1pkn07**
Upgrade https://github.com/KhronosGroup/OpenCL-Headers/pull/47

with my review applied

### CODE REVIEW

**Comment by MathiasMagnus** [comment]
@sl1pkn07 I took your PR as a starting point and built on top of it a comprehensive CMake package configuration of all the Khronos hosted OpenCL repos (Headers, HeadersCpp, ICDLoader) and made them coherent. However, the CLA in the resulting PR still needs your signature (don't know why, since you signed here already). If you could sign it from your part [here](https://github.com/KhronosGroup/OpenCL-Headers/pull/107), I could keep attribution on the commit.

**Comment by sl1pkn07** [comment]
sorry. i don't have any knowledge about conan

signed

greetings

**Comment by bashbaug** [comment]
@MathiasMagnus can we also close this PR now that #170 has been merged?

**Comment by MathiasMagnus** [comment]
Yes we can. The first commit of #170 is this very work. The rest is just building on top.

**Pull request closed without merging**
