### PR TITLE
Remove unnecessary semicolons

### PR DESCRIPTION
**Pull request by kcencele**
Signed-off-by: Maciej Dziuban <maciej.dziuban@intel.com>

### CODE REVIEW

**Comment by bashbaug** [comment]
LGTM, but needs the CLA signed before merging.

**Comment by kcencele** [comment]
> LGTM, but needs the CLA signed before merging.

I did it but it still look like without CLA sign. Could you check why is that?

**Comment by bashbaug** [comment]
> I did it but it still look like without CLA sign. Could you check why is that?

@outofcontrol can you please check the CLA status for this PR?  Thanks!

**Comment by Khronoswebmaster** [comment]
CLA assistant seems to be having some issues. I'm unable to login to their site to verify this submission. There is an open issue [here](https://github.com/cla-assistant/cla-assistant/issues/468), please feel free to add to it.

**Comment by Khronoswebmaster** [comment]
@kcencele has @DziubanMaciejIntel signed off as well?

**Comment by alycm** [comment]
Note that this will be superceded by https://github.com/KhronosGroup/OpenCL-Headers/pull/65 (but that is currently WIP).

**Comment by bashbaug** [comment]
This PR was superseded by #65, which is now merged.

**Pull request closed without merging**
