### PR TITLE
Amd specific exts

### PR DESCRIPTION
**Pull request by 4ngry**
Add AMD specific APIs and defines available for a long time under https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime.

### CODE REVIEW

**Comment by kpet** [comment]
Thanks for contributing this! I agree it would be great to have these definitions upstream. A few comments:
- It seems this PR has the NVidia definitions from #118 as well. I assume that was not intended.
- You will need to sign the CLA before we can accept the contribution.
- These being vendor definitions, a review from AMD and NVidia will be needed (cc @nikhiljnv @b-sumner)
- These definitions should be added to the XML file describing all API definitions (https://github.com/KhronosGroup/OpenCL-Docs/blob/master/xml/cl.xml)

**Comment by nikhiljnv** [comment]
l looked at NVIDIA extension specific defines. Seem ok to me. But, there are few more changes that I need to upstream. So, wouldn't mind dropping these from this change and I can take care of this.

**Comment by 4ngry** [comment]
Ok, it seems that I signed CLA already but some misconfiguration with git username and github username prevents the signing.
I will do the required work on xml documentation too.

**Comment by bashbaug** [comment]
I don't have much to add to the comments above, so I'll just reiterate:

* Thanks for doing this!  It'll be great to have all of these extensions in one place vs. scattered in vendor SDKs.
* Since these are AMD extensions they should have a review from someone from AMD (re-ping @b-sumner @saleelk).
* We also need to add these definitions to the API XML file, especially if we move to auto-generated extension headers (see #113).  I can take care of this, just re-mentioning it for completeness.
* There are a few additional extensions mentioned in [this gist](https://gist.github.com/ranisalt/af4f803f498ab8b3190d3754b2c78ff6#file-rocm-opencl-headers-patch) that we could consider adding to this PR, or could add in a subsequent PR.

Thanks again!

**Pull request closed without merging**
